version: "3.8"
services:
  magnolia:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - vault
    environment:
      VAULT_TOKEN: myroot
    ports:
      - 8080:8080

  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_TOKEN: myroot
      VAULT_ADDR: "http://localhost:8200"
    ports:
      - 8200:8200

